version: '3.8'
services:
  grafana:
    user: root
    container_name: 'miradorstack-integration-grafana'
    image: grafana/grafana-enterprise:12.2.0
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      # Mount both plugins into the Grafana plugins directory
      - ./app/dist:/var/lib/grafana/plugins/miradorstack-miradorexplorer-app
      - ./datasource/dist:/var/lib/grafana/plugins/miradorstack-miradorcoreconnector-datasource
      # Provisioning files (optional, if needed)
      - ./app/provisioning:/etc/grafana/provisioning/app
      - ./datasource/provisioning:/etc/grafana/provisioning/datasource
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.miradorstack-miradorcoreconnector-datasource:debug,plugin.miradorstack-miradorexplorer-app:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: miradorstack-miradorcoreconnector-datasource,miradorstack-miradorexplorer-app
