services:
  grafana:
    # Force multi-arch images to match Apple Silicon when necessary
    platform: linux/arm64
    build:
      args:
        # Grafana images are multi-arch beginning in recent tags; keep explicit for clarity
        grafana_version: ${GRAFANA_VERSION:-12.2.0}
        development: ${DEVELOPMENT:-true}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    environment:
      # Make sure plugin dev mode stays on by default in local runs
      GF_DEFAULT_APP_MODE: development
      # Maximize log verbosity for plugin loading and signature validation
      GF_LOG_LEVEL: debug
      # logger=level pairs (space-separated); cover all plugin namespaces
      GF_LOG_FILTERS: "plugins=debug plugins.*=debug plugin.*=debug"
